name: Labeler

on:
  pull_request:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Label PR based on title
        id: label_pr
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          
          if [[ "$PR_TITLE" == *"bug"* ]]; then
            LABEL="bug"
          elif [[ "$PR_TITLE" == *"feature"* ]]; then
            LABEL="feature"
          else
            LABEL="no-label"
          fi

          echo "Label to apply: $LABEL"
          echo "::set-output name=label::$LABEL"

      - name: Apply the label
        uses: actions/github-script@v6
        with:
          script: |
            const label = '${{ steps.label_pr.outputs.label }}';
            if (label !== "no-label") {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [label]
              });
            }
